// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ZvWDgFqJY1_256mqJpTWjr92Gln7sqk',
    appId: '1:803750883732:web:3bf5ed291b42478be31f81',
    messagingSenderId: '803750883732',
    projectId: 'auth-flutterer',
    authDomain: 'auth-flutterer.firebaseapp.com',
    storageBucket: 'auth-flutterer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApWbSYhUyRFyMbAEOWN2t3Y8hAJMU6Qp8',
    appId: '1:803750883732:android:a18f074fa824de8fe31f81',
    messagingSenderId: '803750883732',
    projectId: 'auth-flutterer',
    storageBucket: 'auth-flutterer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf59fq8izRPrt2yZC_y26b1T4Mmj5LUsI',
    appId: '1:803750883732:ios:b7016ff57517ea75e31f81',
    messagingSenderId: '803750883732',
    projectId: 'auth-flutterer',
    storageBucket: 'auth-flutterer.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf59fq8izRPrt2yZC_y26b1T4Mmj5LUsI',
    appId: '1:803750883732:ios:b7016ff57517ea75e31f81',
    messagingSenderId: '803750883732',
    projectId: 'auth-flutterer',
    storageBucket: 'auth-flutterer.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-ZvWDgFqJY1_256mqJpTWjr92Gln7sqk',
    appId: '1:803750883732:web:358af2e9601a6db7e31f81',
    messagingSenderId: '803750883732',
    projectId: 'auth-flutterer',
    authDomain: 'auth-flutterer.firebaseapp.com',
    storageBucket: 'auth-flutterer.firebasestorage.app',
  );
}
